# Generated by Django 4.2.4 on 2023-08-30 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import power_365.utils.helpers
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Country name")),
                ("iso3", models.CharField(blank=True, max_length=5, null=True, verbose_name="iso3")),
                ("iso2", models.CharField(blank=True, max_length=5, null=True, verbose_name="iso2")),
                ("numeric_code", models.CharField(blank=True, max_length=5, null=True, verbose_name="numeric_code")),
                ("phone_code", models.CharField(max_length=255, verbose_name="Country phone code")),
                ("capital", models.CharField(blank=True, max_length=255, null=True, verbose_name="Country capital")),
                ("currency", models.CharField(blank=True, max_length=255, null=True, verbose_name="Country currency")),
                (
                    "currency_name",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Country currency_name"),
                ),
                (
                    "currency_symbol",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Country currency symbol"),
                ),
                ("tld", models.CharField(blank=True, max_length=255, null=True, verbose_name="Country tld")),
                ("native", models.CharField(blank=True, max_length=255, null=True, verbose_name="Country native")),
                ("region", models.CharField(blank=True, max_length=255, null=True, verbose_name="Country region")),
                (
                    "sub_region",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Country sub-region"),
                ),
                (
                    "timezones",
                    models.JSONField(blank=True, max_length=255, null=True, verbose_name="Country timezones"),
                ),
                (
                    "translations",
                    models.JSONField(blank=True, max_length=255, null=True, verbose_name="Country translations"),
                ),
                ("latitude", models.CharField(blank=True, max_length=20, null=True, verbose_name="latitude")),
                ("longitude", models.CharField(blank=True, max_length=20, null=True, verbose_name="longitude")),
                ("emoji", models.CharField(blank=True, max_length=255, null=True, verbose_name="Country emoji")),
                ("emojiU", models.CharField(blank=True, max_length=255, null=True, verbose_name="Country emojiU")),
                (
                    "wikiDataId",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Country wikiDataId"),
                ),
            ],
            options={
                "ordering": ["-date_modified"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("key", models.CharField(max_length=255, unique=True, verbose_name="Setting key")),
                ("value", models.CharField(max_length=255, verbose_name="Setting value")),
            ],
            options={
                "ordering": ["-date_modified"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="State name")),
                ("state_code", models.CharField(blank=True, max_length=5, null=True, verbose_name="state_code")),
                ("iso2", models.CharField(blank=True, max_length=5, null=True, verbose_name="iso2")),
                ("type", models.CharField(blank=True, max_length=5, null=True, verbose_name="type")),
                ("latitude", models.CharField(blank=True, max_length=20, null=True, verbose_name="latitude")),
                ("longitude", models.CharField(blank=True, max_length=20, null=True, verbose_name="longitude")),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.country")),
            ],
            options={
                "ordering": ["-date_modified"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("file", models.FileField(upload_to=power_365.utils.helpers.scramble_uploaded_filename)),
                ("size", models.IntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image", "image"),
                            ("video", "video"),
                            ("audio", "audio"),
                            ("document", "document"),
                            ("other", "other"),
                        ],
                        default="other",
                        max_length=100,
                    ),
                ),
                ("caption", models.TextField(default="")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_modified"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="City name")),
                ("latitude", models.CharField(blank=True, max_length=20, null=True, verbose_name="latitude")),
                ("longitude", models.CharField(blank=True, max_length=20, null=True, verbose_name="longitude")),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.country")),
                (
                    "state",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.state"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_modified"],
                "abstract": False,
            },
        ),
    ]
